## 1. 查看 Python 版本

`!python -V` 是 IPython 魔术命令,确认解释器版本与 NumPy 篇一致。

In [35]:
!python -V

Python 3.10.20

## 2. 创建 Series

`Series(data, index, dtype, name, copy)` 是一维**带标签**的数组。
在 Notebook 中单独写一个变量名即可自动渲染出带索引的表格。

In [40]:
# pandas.Series(data = None, index = None, dtype = None, name = None, copy = False, fastpath = False)
from pandas import Series  # 只导入需要的类
ser = Series([1,2,3,4,5])  # 用列表创建,索引默认为 0~4
ser  # 单独一行输出 Series,Notebook 会自动渲染成表格
# print(ser)

0    1
1    2
2    3
3    4
4    5
dtype: int64

## 3. 用字典创建 Series

字典的**键作为索引**、值作为数据,所以索引是字符串 `'a'`~`'e'` 而不是 0~4。

In [42]:
ser = Series({'a':1,'b':2,'c':3,'d':4,'e':5})  # 字典的键作为索引,值作为数据
ser

a    1
b    2
c    3
d    4
e    5
dtype: int64

## 4. 指定自定义索引

`index` 参数替换默认索引。数据长度与索引长度必须一致,否则会报错。

In [44]:
ser = Series([1,2,3,4,5],index=[2,3,4,5,6])  # index 指定索引标签,长度必须与数据一致
ser

2    1
3    2
4    3
5    4
6    5
dtype: int64

## 5. 取出数据与索引

- `ser.values`:底层 `ndarray` 数据,失去标签。
- `ser.index`:索引对象(`Index` 类型)。

In [46]:
print(ser.values)  # 取底层 ndarray 数据,标签被丢弃
print(ser.index)  # 取索引对象

[1 2 3 4 5]
Index([2, 3, 4, 5, 6], dtype='int64')

## 6. 打印 Series 与按标签取值

`ser[3]` 是按**索引标签**取值。若想按位置(忽略标签)取值,应使用 `ser.iloc[3]`。

In [48]:
print(ser)
print(ser[3])  # 中括号按索引标签取值,不是按位置
print(ser[4])  # 想按位置取应用 ser.iloc[4]

2    1
3    2
4    3
5    4
6    5
dtype: int64
2
3

## 7. Series 的常用属性

- `dtype`:元素类型。
- `shape`:形状,一维为 `(5,)`。
- `nbytes`:底层数据占用的字节数,可用 `memory_usage()` 看更完整的内存占用。

In [50]:
print(ser.dtype)  # 元素数据类型
print(ser.shape)  # 形状,一维长度为 5 时是 (5,)
print(ser.nbytes)  # 底层数据占用的字节数

int64
(5,)
40

## 8. Series 的算术与成员运算

- 与标量运算:逐元素计算。
- 两个 Series 运算:**按索引标签对齐**后再计算。
- `in` 判断标签是否存在,返回单个布尔值。
- `ser[ser > 3]`:布尔索引,按条件筛选元素。

In [51]:
ser = Series([1,2,3,4,5])  # 第一个 Series
ser_2 = Series([1,2,3,4,5])  # 内容相同、索引也相同的第二个 Series
print(ser+1)  # 与标量运算,标量广播到每个元素
print('*'*10)
print(ser-1)
print('*'*10)
print(ser*2)
print('*'*10)
print(ser/2)  # 与标量运算,结果为浮点
print('*'*10)
print(ser+ser_2)  # 两个 Series 运算:先按索引对齐再逐元素相加
print('*'*10)
print(ser-ser_2)
print('*'*10)
print(ser*ser_2)
print('*'*10)
print(ser/ser_2)  # 按索引对齐后相除
print('*'*10)
print(3 in ser)  # 判断索引标签 3 是否存在,返回单个布尔值
print('*'*10)
print(ser[ser>3])  # 布尔索引:用条件筛选出大于 3 的元素

0    2
1    3
2    4
3    5
4    6
dtype: int64
**********
0    0
1    1
2    2
3    3
4    4
dtype: int64
**********
0     2
1     4
2     6
3     8
4    10
dtype: int64
**********
0    0.5
1    1.0
2    1.5
3    2.0
4    2.5
dtype: float64
**********
0     2
1     4
2     6
3     8
4    10
dtype: int64
**********
0    0
1    0
2    0
3    0
4    0
dtype: int64
**********
0     1
1     4
2     9
3    16
4    25
dtype: int64
**********
0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
dtype: float64
**********
True
**********
3    4
4    5
dtype: int64

## 9. 创建 DataFrame 与字典数据

`DataFrame(data, index, columns, dtype, copy)` 是二维带行列标签的数据结构。

这里用的是最常见的构造方式:字典的键是列名、值是该列的数据。
单独写 `dic` 会以键值对形式输出。

In [53]:
# pandas.DataFrame(data, index, columns, dtype, copy)
from pandas import DataFrame  # 导入 DataFrame 类
import pandas as pd  # 同时保留最常用的别名 pd
dic = {'姓名':['小千','小峰','小亮','小可'],  # 字典结构:外层键是列名,内层列表是该列的数据
       '性别':['男','男','男','女'],
       '数学成绩':[89,90,98,94],
       '语文成绩':[81,87,93,95]}
dic  # 直接输出字典查看结构

{'姓名': ['小千', '小峰', '小亮', '小可'],
 '性别': ['男', '男', '男', '女'],
 '数学成绩': [89, 90, 98, 94],
 '语文成绩': [81, 87, 93, 95]}

## 10. 用 columns 指定列顺序

`columns` 决定列的顺序与是否保留。即使 `dic` 中键的顺序不同,也会按 `columns`
重新排列,`dic` 中存在但 `columns` 未列出的键会被丢弃。

In [54]:
df = DataFrame(dic,columns=['性别','姓名','语文成绩','数学成绩'])  # columns 决定列的顺序;未列出的键会被丢弃
df

  性别  姓名  语文成绩  数学成绩
0  男  小千    81    89
1  男  小峰    87    90
2  男  小亮    93    98
3  女  小可    95    94

## 11. DataFrame 的列访问与 iloc

- `df['姓名']`:按**列名**取 Series。
- `df.iloc[[2]]`:按**位置**取行,`2` 表示第 3 行(位置从 0 开始计数)。
  对应的标签版本是 `df.loc`。

In [56]:
from pandas import DataFrame
import pandas as pd
dic = {'姓名':['小千','小峰','小亮','小可'],
       '性别':['男','男','男','女'],
       '数学成绩':[89,90,98,94],
       '语文成绩':[81,87,93,95]}
df = DataFrame(dic)  # 不指定 columns,列顺序沿用 dic 的键顺序
print(df)
print('*'*10)
print(df['姓名'])  # 按列名取列,结果是 Series
print('*'*10)
print(df.iloc[[2]])  # iloc 按位置取行,2 表示第 3 行;按标签取行应用 loc

   姓名 性别  数学成绩  语文成绩
0  小千  男    89    81
1  小峰  男    90    87
2  小亮  男    98    93
3  小可  女    94    95
**********
0    小千
1    小峰
2    小亮
3    小可
Name: 姓名, dtype: object
**********
   姓名 性别  数学成绩  语文成绩
2  小亮  男    98    93

## 12. 新增一列

`df['评价'] = '优'` 会新建"评价"列;若该列已存在则是**整列覆盖**赋值。
标量 `'优'` 会广播到所有行。

In [59]:
df['评价']='优'  # 列不存在则新增,标量会广播到所有行
df

   姓名 性别  数学成绩  语文成绩 评价
0  小千  男    89    81  优
1  小峰  男    90    87  优
2  小亮  男    98    93  优
3  小可  女    94    95  优

## 13. 覆盖已有列的值

重复给已存在的列赋值会原地覆盖原值,不会新增列。
注意这修改了 `df`,后续单元看到的是新值。

In [60]:
df['评价']='良'  # 列已存在,这里是整列覆盖赋值,不会新增列
df

   姓名 性别  数学成绩  语文成绩 评价
0  小千  男    89    81  良
1  小峰  男    90    87  良
2  小亮  男    98    93  良
3  小可  女    94    95  良

## 14. 用 iloc 定位并整行覆盖

`df.iloc[[2]] = [...]` 把第 3 行的**所有列**替换为右侧列表的值,
右侧元素个数必须与 `df` 的列数一致,否则会报长度不匹配。

In [62]:
df.iloc[[2]]=['小明','女','93','99','优']  # 按位置定位第 3 行并整行覆盖,元素个数需与列数一致
df

   姓名 性别 数学成绩 语文成绩 评价
0  小千  男   89   81  良
1  小峰  男   90   87  良
2  小明  女   93   99  优
3  小可  女   94   95  良

## 15. drop 删除行

`df.drop(2, axis=0)` 按**索引标签** 2 删除行,`axis=0` 表示沿行方向删除。
它返回**新对象**,不传 `inplace=True` 不会改动原 `df`。

In [63]:
df = df.drop(2,axis=0)  # axis=0 表示按行删除,参数是索引标签;返回新对象
df

   姓名 性别 数学成绩 语文成绩 评价
0  小千  男   89   81  良
1  小峰  男   90   87  良
3  小可  女   94   95  良

## 16. drop 删除列

`df.drop('评价', axis=1)` 中 `axis=1` 表示沿列方向,即删除名为"评价"的列。

In [64]:
df = df.drop('评价',axis=1)  # axis=1 表示按列删除,参数是列名
df

   姓名 性别 数学成绩 语文成绩
0  小千  男   89   81
1  小峰  男   90   87
3  小可  女   94   95

## 17. 列数不匹配会产生缺失值

`columns` 列出了 6 列,但 `dic` 只有 5 个键,pandas 用 `NaN` 补齐缺失的列。
这就是后面 `fillna` 要处理的数据质量问题。

In [65]:
from pandas import DataFrame
import pandas as pd
dic = {'姓名':['小千','小峰','小亮','小可'],
       '性别':['男','男','男','女'],
       '数学成绩':[89,90,98,94],
       '语文成绩':[81,87,93,95],
       '评价':['良','良','优','良']
      }
df = DataFrame(dic,columns=['姓名','性别','数学成绩','语文成绩','评价','平均成绩'])  # columns 列出了平均成绩,但 dic 里没有这个键,该列全部为 NaN
df

   姓名 性别  数学成绩  语文成绩 评价 平均成绩
0  小千  男    89    81  良  NaN
1  小峰  男    90    87  良  NaN
2  小亮  男    98    93  优  NaN
3  小可  女    94    95  良  NaN

## 18. fillna 填充缺失值

`df.fillna(0)` 把所有 `NaN` 替换为 0,让"平均成绩"列从缺失变为 0。

真实项目中通常按列用不同策略填充(均值/中位数/众数),而不是一律填 0。

In [66]:
df = df.fillna(0)  # 把所有 NaN 替换为 0
df

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_36528\1506016063.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.fillna(0)

   姓名 性别  数学成绩  语文成绩 评价  平均成绩
0  小千  男    89    81  良     0
1  小峰  男    90    87  良     0
2  小亮  男    98    93  优     0
3  小可  女    94    95  良     0

## 19. df.T 转置

`.T` 把行与列互换,4 行 6 列转置后变为 6 行 4 列,
便于把每个字段看作一行来分析。

In [67]:
df.T  # 转置:行与列互换,4 行 6 列变成 6 行 4 列

       0   1   2   3
姓名    小千  小峰  小亮  小可
性别     男   男   男   女
数学成绩  89  90  98  94
语文成绩  81  87  93  95
评价     良   良   优   良
平均成绩   0   0   0   0

## 20. 准备两个相同的 DataFrame

用二维列表创建 4x5 的表,列名为 `A`~`E`,并复制成 `df_1`、`df_2` 用于演示运算。
列表中出现 0,后续做除法时会被 0 除。

In [70]:
from pandas import DataFrame
import pandas as pd
list1 = [[1,2,3,4,5],[6,7,8,9,0],[2,4,6,8,0],[1,3,5,7,9]]  # 二维列表:4 行 5 列,其中含有 0
df_1 = DataFrame(list1,columns = ['A','B','C','D','E'])  # 用列名列表给 5 列命名
df_2 = DataFrame(list1,columns = ['A','B','C','D','E'])  # 建一个结构相同的表用于对比运算
print(df_1,'\n')
print(df_2)

   A  B  C  D  E
0  1  2  3  4  5
1  6  7  8  9  0
2  2  4  6  8  0
3  1  3  5  7  9

   A  B  C  D  E
0  1  2  3  4  5
1  6  7  8  9  0
2  2  4  6  8  0
3  1  3  5  7  9

## 21. DataFrame 的算术运算

两个形状、列名都相同的 DataFrame 逐元素运算。
**任一位置为 0 时**,除法会得到 `inf` 或 `NaN`,这也是下一节要处理的问题。

In [71]:
print(df_1 + df_2)  # 逐元素相加
print('*'*10)
print(df_1 - df_2)  # 逐元素相减
print('*'*10)
print(df_1 * df_2)  # 逐元素相乘
print('*'*10)
print(df_1 / df_2)  # 逐元素相除,分母为 0 的位置会得到 inf 或 NaN

    A   B   C   D   E
0   2   4   6   8  10
1  12  14  16  18   0
2   4   8  12  16   0
3   2   6  10  14  18
**********
   A  B  C  D  E
0  0  0  0  0  0
1  0  0  0  0  0
2  0  0  0  0  0
3  0  0  0  0  0
**********
    A   B   C   D   E
0   1   4   9  16  25
1  36  49  64  81   0
2   4  16  36  64   0
3   1   9  25  49  81
**********
     A    B    C    D    E
0  1.0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0  NaN
2  1.0  1.0  1.0  1.0  NaN
3  1.0  1.0  1.0  1.0  1.0

## 22. 准备 DataFrame 与 Series 对齐实验

创建 4x5 的 `df_1`,以及索引为 `A`~`E` 的一维 `ser_1`,
用于演示 DataFrame 与 Series 运算时的按标签对齐。

In [72]:
from pandas import DataFrame,Series
import pandas as pd
list1 = [[1,2,3,4,5],[6,7,8,9,0],[2,4,6,8,0],[1,3,5,7,9]]
df_1 = DataFrame(list1,columns = ['A','B','C','D','E'])  # 4 x 5 的表
print(df_1)
print('*'*10)
ser_1 = Series([1,2,3,4,5],index = ['A','B','C','D','E'])  # 索引与 df_1 的列名一致,后面才能按标签对齐
print(ser_1)

   A  B  C  D  E
0  1  2  3  4  5
1  6  7  8  9  0
2  2  4  6  8  0
3  1  3  5  7  9
**********
A    1
B    2
C    3
D    4
E    5
dtype: int64

## 23. DataFrame 与 Series 运算

两者运算时按**标签对齐**:Series 会沿行方向广播到每一列。
此处 `ser_1` 的索引 `A`~`E` 与 `df_1` 的列名一致,所以每列都参与计算;
若索引不匹配会产生 NaN。

In [74]:
print(df_1 + ser_1)  # DataFrame 与 Series 运算按标签对齐,Series 沿行广播到每一列
print('*'*10)
print(df_1 - ser_1)  # 同上,逐元素相减
print('*'*10)
print(df_1 * ser_1)  # 同上,逐元素相乘
print('*'*10)
print(df_1 / ser_1)  # 同上,逐元素相除

   A  B   C   D   E
0  2  4   6   8  10
1  7  9  11  13   5
2  3  6   9  12   5
3  2  5   8  11  14
**********
   A  B  C  D  E
0  0  0  0  0  0
1  5  5  5  5 -5
2  1  2  3  4 -5
3  0  1  2  3  4
**********
   A   B   C   D   E
0  1   4   9  16  25
1  6  14  24  36   0
2  2   8  18  32   0
3  1   6  15  28  45
**********
     A    B         C     D    E
0  1.0  1.0  1.000000  1.00  1.0
1  6.0  3.5  2.666667  2.25  0.0
2  2.0  2.0  2.000000  2.00  0.0
3  1.0  1.5  1.666667  1.75  1.8

## 24. 重建数据用于统计

重新构造带"评价"列、且 `columns` 多出"平均成绩"的 DataFrame,
作为后续求和、均值等统计运算的基础。

In [75]:
from pandas import DataFrame
import pandas as pd
dic = {'姓名':['小千','小峰','小亮','小可'],
       '性别':['男','男','男','女'],
       '数学成绩':[89,90,98,94],
       '语文成绩':[81,87,93,95],
       '评价':['良','良','优','良']
      }
df = DataFrame(dic,columns=['姓名','性别','数学成绩','语文成绩','评价','平均成绩'])  # 多出的平均成绩列没有数据,整列为 NaN
df

   姓名 性别  数学成绩  语文成绩 评价 平均成绩
0  小千  男    89    81  良  NaN
1  小峰  男    90    87  良  NaN
2  小亮  男    98    93  优  NaN
3  小可  女    94    95  良  NaN

## 25. sum 求和

- `df[['数学成绩', '语文成绩']].sum(axis=1)`:先选两列,再**按行**求和,得到每人的总分。
- `df.sum()`:不传 `axis` 时默认**按列**求和,得到每科的总分。

In [87]:
print(df[['数学成绩', '语文成绩']].sum(axis=1) )  # 先选两列,再按行求和,得到每人的总分
print('\n')
print(df.sum())  # 不传 axis 时默认按列求和,得到每科总分

0    170
1    177
2    191
3    189
dtype: int64


姓名      小千小峰小亮小可
性别          男男男女
数学成绩         371
语文成绩         356
评价          良良优良
平均成绩           0
dtype: object

## 26. mean 求均值

`numeric_only=True` 表示只对数值列求均值,跳过"姓名""性别""评价"这些非数值列,
避免字符串参与平均导致的类型错误。

In [95]:
df.mean(axis=1, numeric_only=True)  # 按行求均值,numeric_only 让非数值列被跳过
df

   姓名 性别  数学成绩  语文成绩 评价 平均成绩
0  小千  男    89    81  良  NaN
1  小峰  男    90    87  良  NaN
2  小亮  男    98    93  优  NaN
3  小可  女    94    95  良  NaN

## 27. 把均值写回新列

把按行均值赋给 `df['平均成绩']`,一次赋值就填补了之前整列的 `NaN`。
这是最常见的"派生新列"写法。

In [97]:
df['平均成绩']=df.mean(axis=1, numeric_only=True)  # 把逐行均值写入新列,顺便覆盖原来的 NaN
df

   姓名 性别  数学成绩  语文成绩 评价  平均成绩
0  小千  男    89    81  良  85.0
1  小峰  男    90    87  良  88.5
2  小亮  男    98    93  优  95.5
3  小可  女    94    95  良  94.5

## 28. 单列最值

`min()` 求最小值、`max()` 求最大值,作用于单个 Series 时返回标量。

In [98]:
print(df['数学成绩'].min())  # 单列最小值,返回标量
print(df['数学成绩'].max())  # 单列最大值,返回标量

89
98

## 29. describe 一次性描述统计

`describe()` 一次返回 count、mean、std、min、25%、50%、75%、max 共 8 项统计量,
是快速查看单列分布最省事的方法。

In [101]:
df['数学成绩'].describe()  # 一次输出 count、mean、std、min、25%、50%、75%、max

count     4.000000
mean     92.750000
std       4.112988
min      89.000000
25%      89.750000
50%      92.000000
75%      95.000000
max      98.000000
Name: 数学成绩, dtype: float64

## 30. groupby 分组

`DataFrame.groupby(by=None, axis=0, level=None, as_index=True, sort=True, ...)`
按某列(或多列)的取值把行分组,之后可对每组使用求和/计数/均值等聚合函数。

单元开头的三引号字符串是 `groupby` 的完整签名速查表。
单独执行 `df.groupby('性别')` 只返回 GroupBy 对象,**不立即做任何计算**。

In [103]:
"""
DataFrame.groupby(by=None,
                 axis=0,
                 level=None,
                 as_index=True,
                 sort=True,
                 group_keys=Treu,
                 squeexe=NoDefault.no_default,
                 observed=False,
                 dropna=True)
"""
df.groupby('性别')  # 按性别分组,只返回 GroupBy 对象,不立即计算

## 31. 查看分组结果

`list(df.groupby('性别'))` 把 GroupBy 对象转成列表,元素是 `(组名, 子 DataFrame)`
二元组,可以直接看到每组包含哪些行。

In [105]:
list(df.groupby('性别'))  # 转成列表,元素为 (组名, 该组 DataFrame) 二元组

[('女',
     姓名 性别  数学成绩  语文成绩 评价  平均成绩
  3  小可  女    94    95  良  94.5),
 ('男',
     姓名 性别  数学成绩  语文成绩 评价  平均成绩
  0  小千  男    89    81  良  85.0
  1  小峰  男    90    87  良  88.5
  2  小亮  男    98    93  优  95.5)]

## 32. 准备含重复行的数据

注意"小峰"重复出现,且两门成绩完全相同,构成一条**完全重复**的记录,
用来演示后面的去重操作。

In [117]:
from pandas import DataFrame
import pandas as pd
dic = {'姓名':['小千','小峰','小峰','小可'],  # 姓名列里有重复的小峰
       '性别':['男','男','男','女'],
       '数学成绩':[89,90,90,94],
       '语文成绩':[81,87,87,95],
       '评价':['良','良','良','良']
      }
df = DataFrame(dic,columns=['姓名','性别','数学成绩','语文成绩','评价','平均成绩'])  # 建立含重复行的表
df

   姓名 性别  数学成绩  语文成绩 评价 平均成绩
0  小千  男    89    81  良  NaN
1  小峰  男    90    87  良  NaN
2  小峰  男    90    87  良  NaN
3  小可  女    94    95  良  NaN

## 33. duplicated 标记重复行

返回布尔 Series,`True` 表示该行与**前面已出现的行**完全重复。
默认 `keep='first'`,即只标记第二次及以后出现的重复项。

In [112]:
df.duplicated()  # 标记重复行,True 表示与前面某行完全相同(默认 keep='first')

0    False
1    False
2     True
3    False
dtype: bool

## 34. drop_duplicates 按列去重

`df.drop_duplicates(['数学成绩'])` 只以"数学成绩"作为判定依据:
数学成绩相同即视为重复,忽略其他列的差异。
不传 `subset` 时按**所有列**判定。

In [118]:
# df.drop_duplicates()  # 不传 subset 时按所有列判定重复
df.drop_duplicates(['数学成绩'])  # 只以数学成绩作为去重依据,其他列的差异被忽略

   姓名 性别  数学成绩  语文成绩 评价 平均成绩
0  小千  男    89    81  良  NaN
1  小峰  男    90    87  良  NaN
3  小可  女    94    95  良  NaN

## 35. keep 参数决定保留哪一条

`keep='last'` 表示重复时保留最后出现的一条(默认是 `'first'` 保留第一条)。

注意:这里只返回结果、没有赋值给 `df`,所以 `df` 本身没有被修改。

In [119]:
df.drop_duplicates(keep='last')  # 重复时保留最后一条;没有赋值给 df,所以原表不变

   姓名 性别  数学成绩  语文成绩 评价 平均成绩
0  小千  男    89    81  良  NaN
2  小峰  男    90    87  良  NaN
3  小可  女    94    95  良  NaN

## 36. 准备排序用的数据

5 行学生成绩数据,用于演示 `sort_values` 的单列排序与多列排序。
单元首行注释是 `sort_values` 的签名速查。

In [122]:
# DataFrame.sort_values(by='#', axis=0, ascending=True, inplace= False, np_position='last')
from pandas import DataFrame
import pandas as pd
dic = {'姓名':['小千','小峰','小亮','小可','小丽'],
       '性别':['男','男','男','女','女'],
       '数学成绩':[89,87,90,94,92],
       '语文成绩':[81,87,87,95,98],
       '评价':['良','良','良','优','优']}
df = DataFrame(dic,columns=['姓名','性别','数学成绩','语文成绩','评价'])  # 建立 5 行的成绩表用于排序演示
df

   姓名 性别  数学成绩  语文成绩 评价
0  小千  男    89    81  良
1  小峰  男    87    87  良
2  小亮  男    90    87  良
3  小可  女    94    95  优
4  小丽  女    92    98  优

## 37. sort_values 单列排序

先新增"总成绩"列(数学 + 语文),再按它降序排列。
`ascending=False` 表示从大到小;`sort_values` 默认返回新对象。

In [124]:
df['总成绩'] = df['数学成绩'] + df['语文成绩']  # 新增总分列
df = df.sort_values(by = '总成绩',ascending = False)  # 按总成绩降序排列,返回新对象
df

   姓名 性别  数学成绩  语文成绩 评价  总成绩
4  小丽  女    92    98  优  190
3  小可  女    94    95  优  189
2  小亮  男    90    87  良  177
1  小峰  男    87    87  良  174
0  小千  男    89    81  良  170

## 38. 多列(多级)排序

`by` 传列表表示**依次**按多列排序,`ascending` 也需传列表且长度对应:
先按"性别"降序,性别相同的再按"总成绩"降序。

In [125]:
df = df.sort_values(by = ['性别','总成绩'],ascending=[False,False])  # 多级排序:先按性别,性别相同的再按总成绩,两者都降序
df

   姓名 性别  数学成绩  语文成绩 评价  总成绩
2  小亮  男    90    87  良  177
1  小峰  男    87    87  良  174
0  小千  男    89    81  良  170
4  小丽  女    92    98  优  190
3  小可  女    94    95  优  189

## 39. 用 NumPy 生成模拟数据

先建空 DataFrame,再逐列用 `np.random` 赋随机值。
`np.random.choice` 可从给定候选列表中**等概率**抽取,比手写循环高效。

In [127]:
import pandas as pd
import numpy as np
df = pd.DataFrame()  # 先建空表
size = 100  # 数据行数
df['ID']=np.random.randint(100000,200000,size)  # 随机整数列,范围 [100000, 200000)
df['年龄']=np.random.randint(0,100,size)  # 随机年龄 0~99
df['体重']=np.random.randint(3,150,size)  # 随机体重
df['职业']=np.random.choice(['医生','教师','工程师','职员','高管','自由职业'],size)  # 从 6 种职业中等概率随机抽取
df['学历']=np.random.choice(['高中','大专','大学','硕士','博士'],size)  # 从 5 种学历中随机抽取
df['工资']=np.random.randint(3000,30000,size)  # 随机工资
print(type(df))  # 确认对象类型是 DataFrame
df

<class 'pandas.core.frame.DataFrame'>

        ID  年龄   体重    职业  学历     工资
0   122513  68   62    职员  高中   6343
1   189338  22    7  自由职业  博士  18954
2   120423  96   74    高管  大专  14777
3   184261  36   36    医生  大专  20886
4   152531   9   66    医生  硕士   9698
..     ...  ..  ...   ...  ..    ...
95  133538  90   12   工程师  高中  22529
96  180917  15   17    教师  大专   5099
97  155294  89   98    医生  高中  29164
98  119238  81  101    职员  大专   8875
99  151631  62  121    教师  硕士  11391

[100 rows x 6 columns]

## 40. rank 排名(method 控制并列处理)

`rank()` 返回的是排名数值,而不是重新排序后的数据:

- `method='first'`:并列时按出现顺序给不同名次。
- `ascending=False`:数值越大名次越小。

In [128]:
# DataFrame.rank(axis=0, method='average', numeric_only=None, na_option='keep',ascending=True, pct=False)
df = df.sort_values(by='工资',ascending = False)  # 先按工资从高到低排列
df['顺序排名'] = df['工资'].rank(method='first',ascending=False)  # method='first' 让工资相同的行也得到不同名次
df

        ID  年龄   体重    职业  学历     工资   顺序排名
84  137657  61   48  自由职业  大学  29499    1.0
37  139860  24  143   工程师  大学  29420    2.0
97  155294  89   98    医生  高中  29164    3.0
16  199921   5  121    教师  大学  28665    4.0
7   120531  59   80    高管  博士  28062    5.0
..     ...  ..  ...   ...  ..    ...    ...
74  162404  39   51    高管  博士   4195   96.0
73  195270  38   78  自由职业  大学   3583   97.0
51  145919  59   26    职员  大专   3530   98.0
75  111360  79    4    医生  大专   3313   99.0
41  160945  16  127    教师  大专   3077  100.0

[100 rows x 7 columns]

## 41. rank 默认的平均排名

不传 `method` 时默认 `method='average'`:并列项目取平均名次,
例如名次 1、2、2 会得到 1.0、2.5、2.5。

In [129]:
df['平均工资'] = df['工资'].rank(ascending=False)  # 不传 method 时默认 average,并列名次取平均值
df

        ID  年龄   体重    职业  学历     工资   顺序排名   平均工资
84  137657  61   48  自由职业  大学  29499    1.0    1.0
37  139860  24  143   工程师  大学  29420    2.0    2.0
97  155294  89   98    医生  高中  29164    3.0    3.0
16  199921   5  121    教师  大学  28665    4.0    4.0
7   120531  59   80    高管  博士  28062    5.0    5.0
..     ...  ..  ...   ...  ..    ...    ...    ...
74  162404  39   51    高管  博士   4195   96.0   96.0
73  195270  38   78  自由职业  大学   3583   97.0   97.0
51  145919  59   26    职员  大专   3530   98.0   98.0
75  111360  79    4    医生  大专   3313   99.0   99.0
41  160945  16  127    教师  大专   3077  100.0  100.0

[100 rows x 8 columns]

## 42. merge 合并

`merge(left, right, how='inner', on=None, left_on=None, right_on=None, ...)`
按一个或多个键把两张表**横向拼接**,类似 SQL 的 JOIN。

单元开头的三引号字符串是完整签名。这里准备两张表:
`df_1` 有数学/语文成绩,`df_2` 只有体育成绩,都以"姓名"为键。

In [130]:
'''
merge(left,
        right,
        how='inner',
        on=None,
        left_on=None,
        right_on=None,
        left_index=False,
        right_index=False,
        sort=False,
        suffixes=('_x','_y'),
        copy=True,
        indicator=False,
        validate=None
'''
from pandas import DataFrame
import pandas as pd
dic_1 = {'姓名':['小千','小峰','小亮','小可','小丽'],  # 左表:姓名、性别、两科成绩、评价
       '性别':['男','男','男','女','女'],
       '数学成绩':[89,87,90,94,92],
       '语文成绩':[81,87,87,95,98],
       '评价':['良','良','优','优','优']}
dic_2 = {'姓名':['小千','小峰','小亮','小可','小丽'],  # 右表:只有姓名和体育成绩
        '体育成绩':[95,87,89,91,89]}
df_1 = DataFrame(dic_1)  # 生成左表
df_2 = DataFrame(dic_2)  # 生成右表
print(df_1)
print('*'*10)
print(df_2)

   姓名 性别  数学成绩  语文成绩 评价
0  小千  男    89    81  良
1  小峰  男    87    87  良
2  小亮  男    90    87  优
3  小可  女    94    95  优
4  小丽  女    92    98  优
**********
   姓名  体育成绩
0  小千    95
1  小峰    87
2  小亮    89
3  小可    91
4  小丽    89

## 43. 按公共列内连接

`pd.merge(df_1, df_2, on='姓名')` 默认 `how='inner'`,
只保留两表"姓名"都能匹配上的行,并把右表的列追加到左侧。

In [131]:
df_merge = pd.merge(df_1,df_2,on='姓名')  # on 指定公共键列,默认 inner 只保留匹配成功的行
df_merge

   姓名 性别  数学成绩  语文成绩 评价  体育成绩
0  小千  男    89    81  良    95
1  小峰  男    87    87  良    87
2  小亮  男    90    87  优    89
3  小可  女    94    95  优    91
4  小丽  女    92    98  优    89

## 44. 调整合并结果的列顺序

用列名列表取子集即可重新排布列,把"评价"列挪到"体育成绩"之后。

In [132]:
df_merge = df_merge[['姓名','性别','数学成绩','语文成绩','体育成绩','评价']]  # 用列名列表取子集,顺便重新排列表的顺序
df_merge

   姓名 性别  数学成绩  语文成绩  体育成绩 评价
0  小千  男    89    81    95  良
1  小峰  男    87    87    87  良
2  小亮  男    90    87    89  优
3  小可  女    94    95    91  优
4  小丽  女    92    98    89  优

## 45. 按索引位置合并

`left_index=True, right_index=True` 表示不按键列,而是直接按**行索引位置**对齐。
本例两表行序一致,所以结果与按键合并相同;行序不一致时会错位。

In [133]:
df_merge = pd.merge(df_1,df_2,right_index=True,left_index=True)  # 两边都按行索引位置对齐,不使用姓名列
df_merge

  姓名_x 性别  数学成绩  语文成绩 评价 姓名_y  体育成绩
0   小千  男    89    81  良   小千    95
1   小峰  男    87    87  良   小峰    87
2   小亮  男    90    87  优   小亮    89
3   小可  女    94    95  优   小可    91
4   小丽  女    92    98  优   小丽    89

## 46. how 指定连接方式

`how='left'` 保留左表全部行,右表匹配不上的位置填 `NaN`。
常用取值:`left` / `right` / `inner`(交集) / `outer`(并集)。

In [135]:
# df_merge = pd.merge(df_1,df_2,on='姓名',right_index=True,left_index=True)  # 同时指定 on 和 index 的写法,容易造成困惑
df_merge = pd.merge(df_1,df_2,on='姓名',how='left')  # left 连接保留左表全部行,右侧匹配不上的填 NaN
df_merge

   姓名 性别  数学成绩  语文成绩 评价  体育成绩
0  小千  男    89    81  良    95
1  小峰  男    87    87  良    87
2  小亮  男    90    87  优    89
3  小可  女    94    95  优    91
4  小丽  女    92    98  优    89

## 47. 时间序列:to_datetime

`pd.to_datetime(arg, errors='raise', dayfirst=False, yearfirst=False, ...)`
把字符串/列表/DataFrame 转成 `DatetimeIndex`。

单元开头的三引号字符串是完整签名。这里用日期列表作为随机数据的索引,
得到一个以时间为索引的 Series,便于后续做时序分析。

In [136]:
'''
pandas.to_datetime(arg,
                    errors='raise',
                    dayfirst=False,
                    yearfirst=False,
                    utc=None,
                    format=None,
                    exact=True,
                    unit=None,
                    infer_datetime_format=False,
                    origin='unix',
                    cache=True)
'''
import numpy as np  # 导入 NumPy 生成随机数据
import pandas as pd
dates=['2022-06-20','2022-06-21','2022-06-22','2022-06-23','2022-06-24','2022-06-25','2022-06-26','2022-06-27']  # 8 个日期字符串
ts = pd.Series(np.random.randn(8),index=pd.to_datetime(dates))  # 用 DatetimeIndex 作索引的标准正态随机序列
ts

2022-06-20   -1.204834
2022-06-21   -1.351317
2022-06-22   -1.343254
2022-06-23   -1.562253
2022-06-24    0.272517
2022-06-25    0.327242
2022-06-26    0.307971
2022-06-27    2.157536
dtype: float64

## 48. 日期格式歧义:yearfirst / dayfirst

`'10/11/12'` 这类日期含义不明确,`to_datetime` 靠参数来消歧:

- `yearfirst=True`:按**年-月-日**解析,结果是 2010-11-12。
- `dayfirst=True`:按**日-月-年**解析,结果是 2012-10-11。

建议生产代码统一使用 `2022-06-20` 或 `format=` 明确指定格式。

In [141]:
# pd.to_datetime('10/11/12',dayfirst = True)  # dayfirst:按 日-月-年 解析,结果是 2012-10-11
# pd.to_datetime('12/10/11',dayfirst = True)
pd.to_datetime('10/11/12',yearfirst = True)  # yearfirst:按 年-月-日 解析,结果是 2010-11-12
# pd.to_datetime('10/11/12')  # 不指定参数时无法消除歧义,可能报错或按猜测解析

Timestamp('2010-11-12 00:00:00')

## 49. 从多个列拼装日期

`to_datetime` 可以直接接收含 `year` / `month` / `day` 列的 DataFrame,
按列组合成日期时间。

In [142]:
import pandas as pd
df = pd.DataFrame({'year':[2015,2016],'month':[2,3],'day':[4,5]})  # 年、月、日分列存放
df

   year  month  day
0  2015      2    4
1  2016      3    5

## 50. 把 DataFrame 转为时间戳

`pd.to_datetime(df)` 会自动识别 `year` / `month` / `day` 列并拼成 `Timestamp`,
结果类型为 `DatetimeIndex`。

In [143]:
pd.to_datetime(df)  # 自动识别 year/month/day 列并拼成 Timestamp

0   2015-02-04
1   2016-03-05
dtype: datetime64[ns]